service: metal-as-a-service

custom:
  config: ${file(./config/${opt:stage}.js):config}
  browserify:
    exclude:
      - aws-sdk

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${self:provider.stage}
  apiKeys:
    - ${opt:stage}-${self:service}-apikey
  environment:
    NODE_ENV: ${opt:stage}
    ENV_VAR_1: ${self:custom.config.envVar1}
  iamRoleStatements: ${file(./infra/iam-role-statements.yml)}

package:
  individually: true
  include: config

plugins:
  - serverless-plugin-browserifier
  - serverless-plugin-warmup

functions:
  bands-get:
    handler: src/functions/bands/get.handler
    warmup: true
    events:
      - http:
          path: v1/bands
          method: get
          cors: true
          private: false